### ISSUE TITLE
fails with most recent game version

### ISSUE THREAD

**Issue by ghost** [Arzaroth/CelestiaSunrise#1]
amon@c18:~/CelestiaSunrise$ CelestiaSunrise.py -s -d mlp_save_prime.dat <<omitted>>

Loading save...
Done !
Parsing XML tree...
Something went wrong, error message:
duplicate attribute: line 1, column 633

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/xmltodict-0.9.0-py3.4.egg/xmltodict.py", line 246, in parse
    parser.ParseFile(xml_input)
TypeError: argument must have 'read' attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/CelestiaSunrise-1.0.0_rc4-py3.4.egg/EGG-INFO/scripts/CelestiaSunrise.py", line 64, in <module>
  File "/usr/local/lib/python3.4/dist-packages/CelestiaSunrise-1.0.0_rc4-py3.4.egg/src/shell/ponyshell.py", line 54, in **init**
    self._xml_handle = XmlHandler(data.decode('utf-8', 'ignore'))
  File "/usr/local/lib/python3.4/dist-packages/CelestiaSunrise-1.0.0_rc4-py3.4.egg/src/xmlhandler.py", line 217, in __init__
    self.xmlobj = xmltodict.parse(clean_string(remove_parent(xml_data)))
  File "/usr/local/lib/python3.4/dist-packages/xmltodict-0.9.0-py3.4.egg/xmltodict.py", line 248, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: duplicate attribute: line 1, column 633

Exiting...

**Comment by Arzaroth** [comment]
I am aware of it, which is present since the 2.2.0n update. The thing is the xml used in the savegame is misformatted (as reported by Expat), and python lacks permissive XML parsing library.

Anyway, I'm working on it, by creating python bindings for the XML parsing library used by the game itself (which is rapidxml), to prevent problems in the future. I'll update this issue when I'm done.

**Comment by ghost** [comment]
oh, i see.
sorry to have bothered you ^^;

**Comment by Arzaroth** [comment]
No problem at all, at least I know someone is using what I've done, and that makes me working even faster :)

**Comment by Arzaroth** [comment]
should be ok now.
